---
- name: Add User
  gather_facts: yes
  hosts: all

  tasks:

  - name: Ensure group "wheel" exists
    group:
      name: wheel
      state: present

  - name: Allow wheel passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add the user 'svc_ansible' with a bash shell, appending the group 'wheel' to the user's group
    user:
      name: svc_ansible
      shell: /bin/bash
      groups: wheel
      append: yes 

  - name: Setup authorized keys for the svc_ansible user 
    authorized_key:
      user: svc_ansible
      key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDu5ArSbyxhQrwBHaa+ItUWdGn5EBdLoUzsB0cHEL99Yd5iIN8YuKavrpfPX47txxlVg4ArU+7XCLZRJVNFmqGF/KJJDpJDkbR8C5GuWv/f4Qk4zSbtHiUoP2vPS6DmipJdBWw65yOOfbIzQ3KBHj0lEmygaSdagK5g+1lAPEUdH9g4Fg4g/6iBinw8NPcEtVf514udM4ckukSJGb7VROv5rMIPPhzQ6iMZHmZYV+rrSarHYi6nXCnU/208c20zLvpFkWJIIrZmi82C7ufLOJUmKY5dA46SMN1Y5eynuyAU9eZWv+fz4J5iYBpS3yzWbnupSMi3e+amqgsmGiR0voCATsUQcFEekoO9K66g995JUl7vmJMH3uWb2jfJCUBiRCdhuw3W7JvtOlvZmJfYWsDzadmQyd2JHYhQHtUZADeLa/dMz9c1tJvtWRQOSjQgehGscgkdj657uwnuPgVZ78EZ3K8MxsqI9UUeKNR6/9EphRBDPPmtwyBnObwB3xYSLjbnCnB6mQ17nGLAZPHdNJiiydtWbm9cMTYKLMIXYmduqt11pnET1EChkTSfXJkjPbYeB+bYaAtC2O+9STMl6mZNee2qCTN8pJiLSYlJGrFynDodvR1rxfZq69FM8baRw0Gpng5LvnIKqKuqANk6JGYtm7gf+yuUuGJn7UN8ae77YQ==