---
- name: Add User
  gather_facts: yes
  hosts: all

  tasks:

  - name: Ensure group "wheel" exists
    group:
      name: wheel
      state: present

  - name: Allow wheel passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add the user 'svc_ansible' with a bash shell, appending the group 'wheel' to the user's group
    user:
      name: svc_ansible
      shell: /bin/bash
      groups: wheel
      append: yes 

  - name: Setup authorized keys for the svc_ansible user 
    authorized_key:
      user: svc_ansible
      key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdTKOlFn7t3cLBVvbZ4d5jpW0tSNOMtouZL14TWS0BiRGfoj6pz3GA8p9gjZDk+FnbVF28PeQCXqAyKQtDCtVuwbWnUAVs+z+Cb8op8aEc/DxDTE6wYMo3BWanKcIsWE41Tyo/6/rjZOw6OrWWbcznn6SU2dxjCqLbGQqrxDtq2OAFqEwvEnuRsaUOJrjBTEtQ55CGJnULNUR5amwj7h6zh854peSYBlhxEmku5fc4my9TTasV4XMVtLy1dNUktFynZ/W7RhTPyBn7bLzhL2y4QMVlh6q4MS8OyPYwqkh6rI60r+cSGfa6HQTRorgDWdOZ/W03VKx0M4TO81VL/zrlKOeKCML5QqghIM7GtCs6OSGr2i2x4WoOwHb6UiRzPC4x/gxjBPKK1yOCDWqekIIMU5Iq7hwcO+UXIBgyvpXSN7AfHIbo4zDCiJs0Ov2DNXlpGqFMckcu1J1ICrmwyWu/ctaAgMXXlxgMMLipKv1CmFcznFld4c5lwk99aPlZU4k=